<a href="https://colab.research.google.com/github/merlinecatharine/MACHINE-LEARNING-PROJECT/blob/main/IRIS_DATA_STANDARDISATION_PREDICTION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

IRIS_DATASET STANDARDISING ,TRAINING AND PREDICTION:
---



TABLE OF CONTENTS:
---
1.STANDARDISING THE IRIS DATASET

2.TRAINING THE MODEL

3.PREDICTING IN IRIS DATASET



STANDARDISING THE IRIS DATASET:
---



Importing required libraries

---



In [ ]:
#importing
import seaborn as sns  #importing seaborn
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
import sklearn.datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

reading dataset

---



In [ ]:
path='/content/IRIS.csv'
df=pd.read_csv('IRIS.csv')

printing dataset

---



In [ ]:
df

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [ ]:
x=df.drop(columns='species',axis=1)
y=df.species



In [ ]:
print(x)

     sepal_length  sepal_width  petal_length  petal_width
0             5.1          3.5           1.4          0.2
1             4.9          3.0           1.4          0.2
2             4.7          3.2           1.3          0.2
3             4.6          3.1           1.5          0.2
4             5.0          3.6           1.4          0.2
..            ...          ...           ...          ...
145           6.7          3.0           5.2          2.3
146           6.3          2.5           5.0          1.9
147           6.5          3.0           5.2          2.0
148           6.2          3.4           5.4          2.3
149           5.9          3.0           5.1          1.8

[150 rows x 4 columns]


In [ ]:
print(y)

0         Iris-setosa
1         Iris-setosa
2         Iris-setosa
3         Iris-setosa
4         Iris-setosa
            ...      
145    Iris-virginica
146    Iris-virginica
147    Iris-virginica
148    Iris-virginica
149    Iris-virginica
Name: species, Length: 150, dtype: object


In [ ]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=3)

In [ ]:
print(x.shape,x_train.shape,x_test.shape)

(150, 4) (120, 4) (30, 4)


In [ ]:
print(df.std())

sepal_length    0.828066
sepal_width     0.433594
petal_length    1.764420
petal_width     0.763161
dtype: float64


In [ ]:
scaler=StandardScaler()

In [ ]:
scaler.fit(x_train)


StandardScaler()

In [ ]:
x_train_standardized=scaler.transform(x_train)

In [ ]:
print(x_train_standardized)

[[-0.04717658  2.19102181 -1.46020619 -1.31097023]
 [-1.30521861  0.78501851 -1.06028014 -1.31097023]
 [ 1.33666966  0.08201686  0.93935012  1.19659028]
 [ 0.95925705 -0.38665091  0.48229177  0.14077533]
 [-1.80843543 -0.38665091 -1.34594161 -1.31097023]
 [-0.8020018   1.01935239 -1.28880931 -1.31097023]
 [ 1.08506126 -0.15231702  0.71082095  0.6686828 ]
 [-1.68263122 -1.79265421 -1.4030739  -1.17899336]
 [ 0.70764865 -0.85531868  0.88221783  0.93263654]
 [ 0.45604024 -2.02698809  0.42515948  0.40472907]
 [ 0.70764865 -0.62098479  1.05361471  1.19659028]
 [-0.04717658 -0.85531868  0.08236572  0.00879846]
 [-1.55682702  1.25368628 -1.57447078 -1.31097023]
 [-0.927806    1.01935239 -1.34594161 -1.17899336]
 [ 0.33023603 -0.15231702  0.65368865  0.80065967]
 [ 0.70764865  0.31635074  0.42515948  0.40472907]
 [-0.927806    0.55068463 -1.17454473 -0.91503963]
 [ 0.20443183 -0.85531868  0.76795324  0.53670593]
 [-0.04717658 -0.85531868  0.76795324  0.93263654]
 [-0.55039339 -0.15231702  0.42

In [ ]:
x_test_standardized=scaler.transform(x_test)

In [ ]:
print(x_train_standardized.std())

1.0


In [ ]:
print(x_test_standardized.std())

1.073087128606895


the dataset is standardised!

---




TRAINING THE MODEL:
---



Importing svm and accuracy_score from sklearn:

---



In [ ]:
from sklearn import svm
from sklearn.metrics import accuracy_score

In [ ]:
#trainig the model
classifier=svm.SVC(kernel='linear')


In [ ]:
classifier.fit(x_train,y_train)

SVC(kernel='linear')

In [ ]:
# MODEL EVALUATION
#accuracy _score
x_train_prediction=classifier.predict(x_train)
training_data_accuracy=accuracy_score(x_train_prediction,y_train)

In [ ]:
print("Accuracy score of training data:",training_data_accuracy)

Accuracy score of training data: 0.9916666666666667


In [ ]:
x_test_prediction=classifier.predict(x_test)
test_data_accuracy=accuracy_score(x_test_prediction,y_test)

In [ ]:
print("Accuracy score of test data:",test_data_accuracy)

Accuracy score of test data: 0.9666666666666667


We got the accuracy for the dataset... :)  

---




PREDICTING IN IRIS DATASET:
---

with sample input from the dataset

In [ ]:
#inputing one data from the dataset to check
input_data=('5.1','3.5','1.4','0.2')

In [ ]:
#changing input data to numpy array
input_data_as_numpy_array=np.asarray(input_data)

In [ ]:
#reshaping /because one data out of it dimension changing to (1,-1)
input_data_reshaped=input_data_as_numpy_array.reshape(1,-1)

In [ ]:
import warnings
warnings.filterwarnings('ignore')

In [ ]:
#standerdise data
std_data=scaler.transform(input_data_reshaped)
print(std_data)

[[-0.927806    1.01935239 -1.34594161 -1.31097023]]


In [ ]:
prediction=classifier.predict(std_data)
print(prediction)

['Iris-setosa']


**THANK YOU!!**